apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-helm-pet-clinic
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ext-pet-clinic-cicd
  template:
    metadata:
      labels:
        app: ext-pet-clinic-cicd
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80